### ISSUE TITLE
Multiple errors

### ISSUE THREAD

**Issue by shishkin** [blongden/vnd.error#1]
What if a request contains several errors that the server can identify and communicate back to the client. Wouldn't it be better to consider an array of error objects?

**Comment by blongden** [comment]
A few people have suggested this and it's a great suggestion. I have modified the spec to include support. Thanks for your feedback.

**Comment by ftassi** [comment]
In a project I'm working on I've used _embedded key to embed multiple errors. I think it make sense, given that this spec is HAL compatible. What do you think?
