### ISSUE TITLE
No "self" link

### ISSUE THREAD

**Issue by kavika13** [blongden/vnd.error#10]
According to http://tools.ietf.org/html/draft-kelly-json-hal:

> Each Resource Object SHOULD contain a 'self' link that corresponds with the IANA registered 'self' relation (as defined by [[RFC5988](http://tools.ietf.org/html/rfc5988)]) whose target is the resource's URI.

`SHOULD` means that is okay that this is missing, but [the full implications must be understood and carefully weighed before choosing a different course](http://tools.ietf.org/html/rfc2119).

**Comment by blongden** [comment]
We're now 100% compatible with the HAL spec, so the self link can be included if it's appropriate to do so.
