### ISSUE TITLE
Shouldn't a link have a "type" attribute?

### ISSUE THREAD

**Issue by pnsantos** [blongden/vnd.error#12]
Hi,

As the title says... shouldn't the link elements have a "type" attribute? I ask because in some cases it may be usefull to include a link to a text/html page and another that returns say a application/hal+json response.

Without the type attribute, it up to the client application to associate/guess/read-on-some-documentation what each link relation points to (thus making the error message just a little less self-descriptive.

**Comment by blongden** [comment]
The spec now extends the HAL specification, which does indeed include a 'type' attribute to hint at the media type expected when following a link relation. See http://tools.ietf.org/html/draft-kelly-json-hal-06#section-5.3
