### ISSUE TITLE
Is the JSON example correct?

### ISSUE THREAD

**Issue by bravo-kernel** [blongden/vnd.error#13]
Hi Ben,

First of all, great job on the standard. I am not 100% sure about this but I have a feeling that the current application/vnd.error+json example in the readme could use an update.

The Constraints in the specification explicitly states that _"The root of a vnd.error representation_ **_MUST_** _be an 'errors' element containing one or more 'error' representations._". 

In the current json example the errors root is missing.

The way I interpret the specification the complete and correct json example should be:

```
{
   "errors":
   [
       {
           "logRef": "42",
           "message": "Validation failed",
           "_links":
           [
               {
                   "help":
                   {
                       "href": "http://...",
                       "title": "Error information"
                   }
               },
               {
                   "describes":
                   {
                       "href": "http://...",
                       "title": "Error description"
                   }
               }
           ]
       }
   ]
}
```

If the above example is correct I would be more than happy to provide you with a patch for the README. If not, could you please explain why.

Thanks in advance and HTH,
  Bravo

**Comment by blongden** [comment]
Hi, this is more specific to the XML representation - where everything must be contained within a root node <errors />.

In JSON the root node can simple be the root object - which is implicitly an array of error objects. JSON is way less specific in this regard.
