### ISSUE TITLE
Consider a profile instead of new media types

### ISSUE THREAD

**Issue by mstade** [blongden/vnd.error#17]
First off – great work! Really nice to see someone spending time looking in to more standardized error representations.

However, as I was reading through the spec and the various issues, I keep thinking that maybe this actually fits better as a profile rather than a media type. Otherwise, if this spec proves successful, there's the risk that there'll be a proliferation of media types that are essentially just copies of each other but with media type specific semantics. The spec already includes two media types – vnd.error+json and vnd.error+xml – and in #14 yet another format is discussed.

Instead I think the spec could just focus on describing the various attributes and link relations, and then this profile could be applied to any format that includes such affordances. HAL obviously already works, you've shown that, but then perhaps others such as HTML, EDN or what have you will work just as well. All you need to do is link to this profile and a client should be able to make sense of the document if it understands this profile and the media type.

**Comment by blongden** [comment]
Thanks for the feedback and apologies for the delay in responding.

This had crossed my mind actually - and I was thinking of doing both. Registering the media type but also allowing this to be represented at application/hal+json with appropriate profile metadata. I think that would satisfy both scenarios.
