### ISSUE TITLE
HAL-flavored links

### ISSUE THREAD

**Issue by shishkin** [blongden/vnd.error#2]
Currently HAL defines links as simple objects, without arrays:

```
"_links": {
    "self": { "href": "/orders" },
    "next": { "href": "/orders?page=2" },
    "search": { "href": "/orders?id={order_id}" }
}
```

It would be more consistent to comply with HAL on it.

**Comment by blongden** [comment]
I half agree. HAL also supports an array of links where required. Have a look at a few of the examples on http://blog.stateless.co/post/13296666138/json-linking-with-hal

It could be that this has been revised in the latest spec though. I would have to check.
