### ISSUE TITLE
error code

### ISSUE THREAD

**Issue by m6w6** [blongden/vnd.error#3]
Is it just me, or ain't an error code attribute missing?

**Comment by blongden** [comment]
Just you :-)

I deliberately do not want an error code in the media type so as not to allow conflict with the HTTP error code. All errors can (and should) be represented using that. If you want to communicate more information, the logref allows you to reference something more specific on the server, and the 'describes' rel is a link for further information.

**Comment by hjr3** [comment]
Maybe error code is the wrong approach, but what about an error slug? We have clients with cross-cutting concerns. Our mobile device may need a short error message due to real-estate, but the desktop website might want the full explanation.

**Comment by hjr3** [comment]
Here is an example of what I mean:

```
[
    {
        "logref": 42,
        "slug": "email"
        "message": "Email address validation failed",
        "_links": {
            "help": [
                { "href":  "http://...", "title": "Error information" }
            ],
            "describes": [
                { "href":  "http://...", "title": "Error description" }
            ]
        }
    }
]
```

Now the client can use the generic error message or map a custom error message to the slug. The custom error message might even be in a different language.

**Comment by blongden** [comment]
Thanks for providing an example - my initial thoughts on the suggestion would be that this may be something that's better handled on the client side anyway - using a translation library of some kind. My concern with having a 'slug' identifier is that it's effectively duplicating the contents of the message field in some way.

**Comment by baldurrensch** [comment]
In my opinion, having a slug or an error number is really the same as having the `title` attribute with the URL: It connects human readable with machine readable information. I could also see it as:

```
[
    {
        "logref": 42,
        "message": {
             "slug": "email",
             "text": "Email address validation failed"
        },
        "_links": {
            "help": [
                { "href":  "http://...", "title": "Error information" }
            ],
            "describes": [
                { "href":  "http://...", "title": "Error description" }
            ]
        }
    }
]
```

But I am totally fine with what @hradtke suggested.

**Comment by blongden** [comment]
I don't want to pollute the error object with too much information. For this reason, I think this should be handled by the client in a different way.
