### ISSUE TITLE
What about retrying request that had generated error response?

### ISSUE THREAD

**Issue by dometec** [blongden/vnd.error#5]
There are correct request from client that generate error, ex. server failure or wrong timing. This request can be resubmitted.

What do you think about a retry flag ( true/false )  or retry time ( retry after 10 sec. ) as attribute of error element? 

The request can be re-submitted when all retry flag of each error element are true, or, in case of time, when max(retrytimes) has passed.

**Comment by baldurrensch** [comment]
Maybe instead of the retry time, a retry after timestamp, removes the burden of calculating when to retry from the client.

**Comment by blongden** [comment]
I like the idea - I think specifying the retry after 10 seconds is more flexible (no need to worry about time zones etc). Thanks for the input!

**Comment by timbunce** [comment]
There's already a [Retry-after http header](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.37). The spec says it "can be used with a 503 (Service Unavailable)" and "This field MAY also be used with any 3xx (Redirection) response". It seems reasonable to recommend it for error responses that want to express a delay before retry.

If there's a real need for this functionality to be defined in vnd.error then using the same semantics as the Retry-after headers seems wise.

**Comment by timbunce** [comment]
I see that [api-problem+json](http://tools.ietf.org/html/draft-nottingham-http-problem-02) references the Retry-After header.

**Comment by borisguery** [comment]
I don't think the error object should be tied to such specific behavior. It is obviously useful but it doesn't fit the error object imho. As mentioned by @timbunce there is a `Retry-After` HTTP header which had been designed exactly for this purpose.

The error object should not be bloated with specific use cases which most likely depends on a specific workflow.

**Comment by blongden** [comment]
I was not aware of the Retry-After HTTP header. It makes a lot of sense to use this rather than duplicate the behaviour in the response body. I'll add some recommendations for this.

**Comment by blongden** [comment]
My only concern would be that the spec limits to the 503 response or a 3xx response. I'll try to come up with an example where you may want a Retry-After on a 4xx response (perhaps there is not a valid one).

**Comment by borisguery** [comment]
mmm, not sure but we may see it in a different maner. Here are some use cases:
- Registration

```
POST /users
Content-Type: application/vnd.acme.user+json
{ "username": "borisguery", "password": "s3cr3ts3cr3t"}
```

Let's say for some reason my username is already used, I may retry some seconds later, but there is a rule in my business domain:

> a failed registration should not be issued more than 1 time per minute.

The server would then reply with:

```
503 Service-Unavailable
Retry-After: 60
Content-Type: application/vnd.error+json
[
    {
        "logref": 123,
        "message": "You have excessed the number of allowed registration process, retry later.",
        "_links": {
            "help": { "href":  "http://...", "title": "Error information" },
            "describes": { "href":  "http://...", "title": "Error description" }
        }
    }
]
```
- Votes

Let's say I've a voting application, but I don't allow users to vote more than 10 per minute.

The same workflow would apply. 

I don't see what's wrong to provide an error object no matter the status is about a server error (500 range) or a so called client error (400 range).

**Comment by borisguery** [comment]
I forgot to say that the semantic meaning of `503 Service Unavailable` seems totally adequate to me with the given use cases.

I do some action but it result in a error (`application/vnd.error`) which makes the Service Unavailable (`status code`).

**Comment by blongden** [comment]
Yes that's what I was trying to say. I mean a use case where a 503 was not appropriate but a Retry-After was required.

I think Retry-After and 503 covers it nicely.

**Comment by dometec** [comment]
I also think that using the http header is appropriate ways. After all when you specify a retry time, it means that your request is correct, but that can not be served at this time, and a 503 is correct.
