### ISSUE TITLE
Confused by the example's link relations

### ISSUE THREAD

**Issue by gabrielf** [blongden/vnd.error#7]
Hi,

I find the link relations used in the example somewhat confusing. This internet draft: http://tools.ietf.org/html/draft-nottingham-http-problem-02 uses the describedBy link relation to provide a link to a resource that, I assume, furthers describe the error. In the vnd.error example "help" seems to serve the same purpose.

I am confused by the "descibes" link relation. What might be returned when resolving it?

**Comment by blongden** [comment]
Hi @gabrielf,

The purpose of the describes link relation is to link to an error on the server that this document is representing (ie, a human readable representation of the error on the server side). It's optional though, so if you do not need it, don't represent it.

The help link rel is the equivalent of the describedBy link relation as you described.

**Comment by blongden** [comment]
I have added some clarification about the link relations to the specification.

**Comment by gabrielf** [comment]
:+1:  Nice!
