### ISSUE TITLE
Current 'Array of error objects' structure is limiting - Building on HAL offers significant improvements

### ISSUE THREAD

**Issue by timbunce** [blongden/vnd.error#8]
The current vnd.error JSON format, as an array of objects, has some significant limitations.
- There's nowhere to put context information that applies to the entire response. It could either go in the first object, making that _special_ in an awkward way, or be duplicated in each error, bloating the response
- There's no natural way to express a hierarchy/cascade of errors. For example, a specific 'transaction error' could have been triggered by an exception from a 'storage layer' which was in turn triggered by a 'disk full' error. These are clearly nested - the inner errors triggering the outer - so it would be wrong to represent them as a list. There may also be more than one error at a given level of nesting. Java is a common source of these kinds of richly nested exceptions.
- As another example of the need for nesting, it should be possible for some kind of 'gateway service' to forward a vnd.error response that it received from a 'backend service' by embedding it in its own vnd.error response.

I suggest that the vnd.error JSON format be changed to an error object that can contain arrays of other embedded objects, including error objects.

The _links item is already modelled after the [HAL Specification](http://tools.ietf.org/html/draft-kelly-json-hal-05) but the current "array of objects" structure of the vnd.error response means it's not compatible with HAL.

I suggest that vnd.error could be significantly improved by building directly on the HAL specification. The key change is to move the array from the outermost level to being an _embedded element.

So this example from the home page:

``` json
[
    {
        "logref": 42,
        "message": "Validation failed",
        "_links": {
            "help": [
                { "href":  "http://...", "title": "Error information" }
            ],
            "describes": [
                { "href":  "http://...", "title": "Error description" }
            ]
        }
    }
]
```

would be expressed as:

``` json
{
    "logref": 42,
    "message": "Validation failed",
    "_links": {
        "help": [
            { "href":  "http://...", "title": "Error information" }
        ],
        "describes": [
            { "href":  "http://...", "title": "Error description" }
        ]
    }
}
```

That's a simple change!

But it gives vnd.error HAL compatibility, so now vnd.error can do this:

```
{
    "logref": 42,
    "message": "Validation failed",
    "_links": {
        "help": [
            { "href":  "http://...", "title": "Error information" }
        ],
        "describes": [
            { "href":  "http://...", "title": "Error description" }
        ]
    }
    "_embedded": {
        "errors": [ # list of error details
            { ... },  # which can be vnd.error objects themselves
            ...
        ],
        "some_other_related_info": {
        }
    }
}
```

**Comment by baldurrensch** [comment]
:+1:

**Comment by gabrielf** [comment]
Looks good!

**Comment by blongden** [comment]
Yes I was pondering this too. It's a simple change that makes it compatible with the HAL format, which is what people seem to want (me too, as it happens).

That does raise the question of should this be a media type in its own right, or should we be serving this as application/hal+json (or xml), with some way of identifying that it conforms to this specification?

**Comment by timbunce** [comment]
I think the correct approach would be for this work to become a "profile" of the application/hal+json media type. Something like:

>  Content-Type: application/hal+json; profile="...something here..."

(I think we'll be seeing lots of 'application/hal+json' profiles defined in future. Let's lead the way!)

See [this post](http://www.mnot.net/blog/2012/04/17/profiles) by Mark Nottingham, including the comments, for some more details.

**Comment by darrelmiller** [comment]
Reporting an error is globally applicable enough to merit its own media type in my opinion.  I have no problem if the vnd.error format followed the hal syntax conventions.  But I don't like the idea of getting content-type application/hal+json and then going hunting elsewhere to find a profile that tells me what the message really means.  As is mentioned by Mark Baker and Jan, in the comments on Mark's post, adding profile does not prevent format proliferation, it just splits the identify into two pieces.

**Comment by darrelmiller** [comment]
The problem with adopting an error format that is completely consistent with the hal spec is that you cannot rely on the context link's relation to provide the semantics of the root hal resource.  This is a key principle in hal.  Surely we don't want to have to update all of our link relation documentation to include information about what properties may be included in a hal error message if following the link fails for some reason.  Follow the basic syntax of hal but I would suggest keeping it a very constrained subset of hal otherwise developers are going to end up using out of band information to access custom data in the representation.

**Comment by blongden** [comment]
I like @timbunce suggestion of making this a profile - but I also agree with @darrelmiller that it probably does warrant its own media type. I wonder if we can register both a profile _and_ a media type to satisfy all requirements...

I'd like to make this syntax compatible with HAL as it's useful to not have to import multiple libraries in to clients to understand the messages (where HAL is the media type used for everything else).

**Comment by blongden** [comment]
The benefit to having the identity split into two pieces is that generic browsers that do not understand your specific profile definition are still able to understand the higher level formatting of the resource (ie - you could still use the HAL browser with this).

**Comment by darrelmiller** [comment]
@blongden I hear you, but I think "dumbing down" the reported media types to help us use generic tools for debugging is kow-towing to the wrong master.  I think we should be fixing the debugging tools to teach them, "when you see media type x treat it as a y".  I realize this probably never going to happen, but at least I feel a bit better now that I've expressed my opinion. :-)

**Comment by blongden** [comment]
Ok - we're HAL compatible...

I'm still pondering the profile vs media type (or both) question though... :)
